ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [

    path('add/<int:Product_id>/',views.add_cart,name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:Product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:Product_id>/',views.full_remove,name='full_remove')

]

ecommerceproject/ecommerceapp/urls.py
from django.urls import path
from . import views

app_name='ecommerceapp'


urlpatterns = [

    path('',views.allprodCat,name='allprodCat'),
    path('<slug:c_slug>/',views.allprodCat,name='Product_by_category'),
    path('<slug:c_slug>/<slug:Product_slug>/',views.proDetail,name='ProdCatdetail')
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include


from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceapp/',include('ecommerceapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns=[

    path('',views.SearchResult,name='SearchResult'),

]

ecommerceproject/cart/models.py
from django.db import models
from ecommerceapp.models import product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    Product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.Product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.Product)

ecommerceproject/ecommerceapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ecommerceapp:Product_by_category',args=[self.slug])


    def __str__(self):
        return '{}'.format(self.name)

class product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecommerceapp:ProdCatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from ecommerceapp.models import product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist



def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,Product_id):
    Product=product.objects.get(id=Product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
                cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(Product=Product,cart=cart)
        if cart_item.quantity < cart_item.Product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            Product=Product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.Product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))




def cart_remove(request,Product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    Product=get_object_or_404(product,id=Product_id)
    cart_item=CartItem.objects.get(Product=Product,cart=cart)
    if  cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,Product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    Product = get_object_or_404(product, id=Product_id)
    cart_item = CartItem.objects.get(Product=Product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/ecommerceapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from ecommerceapp.models import Category, product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.

def allprodCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=product.objects.all().filter(available=True)
    paginator=Paginator( products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,Product_slug):
    try:
        Product=product.objects.get(category__slug=c_slug,slug=Product_slug)
    except Exception as e:
        raise e
    return render(request,'Product.html',{'Product':Product})

ecommerceproject/search_app/views.py
from django.shortcuts import render
from ecommerceapp.models import product
from django.db.models import Q
# Create your views here.


def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,"search.html",{'query':query,'products':products})

ecommerceproject/templates/Product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{Product.description|truncatewords:155}}


{% endblock %}
{% block title %}
    {% if category %}
        {{Product.name}} - New shop
    {% endif %}

{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
        <div class="mx_auto">
            <p><a href="{% url 'ecommerceapp:allprodCat' %}">Home</a> | <a href="{{Product.category.get_url}}">{{Product.category}}</a>|{{Product.name}}</p>
        </div>
<div class="container">
    <br>
    <div class="row" >
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
                <img src="{{Product.image.url}}" alt="{{Product.name}}">
            </div>
        </div>

            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>
                    <h1 class="my_prod_title">{{Product.name}}</h1>
                    <p>${{Product.price}}</p>
                    <p class="my_title">Product Description</p>
                    <p class="text-justify  my_prod_text">{{Product.description}}</p>
                    {% if Product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
                    {% else %}
                    <a class="btn btn-secondary"  href="{% url 'cart:add_cart' Product.id %}">Add to Cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >-->
    <meta name="description" content="{% block metadescription %}{% endblock %}">
     <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js "></script>
     <link href=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" >
     <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/264478aa8d.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<!--<script src="{% static 'js/popper.min.js' %}"></script>-->
<!--<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
<!--<script src="{% static 'slim.min.js' %} " ></script>-->
<script src=" https://code.jquery.com/jquery-3.2.1.slim.min.js "></script>
<script src=" https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js " ></script>
<script src=" https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js " ></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

This is the cart page. proceed to your items and place the order.
{% endblock %}
{% block title %}
    cart -New Shop pvt LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please Click<a href="{% url 'ecommerceapp:allprodCat' %}">Here</a>to continue shopping.

        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
               <th colspan="5">
                   Your Items

               </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.Product.get_absolute_url"><img src="{{cart_item.Product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-lef">
                    {{cart_item.Product.name}}
                    <br>
                    SKU: {{cart_item.Product.id}}
                    <br>
                    Price: ${{cart_item.Product.price}}
                    <br>
                    Qty : {{cart_item.quantity}} x ${{cart_item}}
                </td>
                <td>
                    ${{cart_item.sub_total}}
                </td>
                 {% if cart_item.quantity < cart_item.Product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.Product.id %}" class="custom_a"> <i class="fa-solid fa-plus custom_icon"></i></a>
                    &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.Product.id %}" class="custom_a"><i class="fa-solid fa-minus  custom_icon"></i></a>
                    &nbsp;&nbsp;<a href="{% url 'cart:full_remove' cart_item.Product.id %}" class="custom_a"><i class="fa-solid fa-trash  custom_icon"></i></a>
                </td>
                 {% else %}
                <td>
                    &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.Product.id %}" class="custom_a"><i class="fa-solid fa-minus  custom_icon"></i></a>
                    &nbsp;&nbsp;<a href="{% url 'cart:full_remove' cart_item.Product.id %}" class="custom_a"><i class="fa-solid fa-trash  custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shoping cart items before proceeding with the order place.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total is :$ <strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerceapp:allprodCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
    {% endif %}
</div>

</div>

{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welcome to New shop Where you can buys anything....
    {% endif %}
{% endblock %}
{% block title %}
{% if category %}
        {{category.name}} - New shop
    {% else %}
        see our new collection-New shop
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'ecommerceapp:allprodCat' %}">Our Product Collections</a></p>
            </div>
        </div>
    </div>
    {% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
     <br>
<div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text_justify">{{category.description}}</p>
</div>
        {% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/gadg.png' %}" alt="Our products" width="1500px;" height="500px;">
</div>

<div>
    <h1 class="text-center my_title">Our product collections</h1>
    <p class="text-justify">It was originally taken from a Latin text written by a Roman Scholar, Sceptic and Philosopher by the name of Marcus Tullius Cicero, who influenced the Latin language greatly.
        The "filler" text we know today has been altered over the years (in fact "Lorem" isn't actually a Latin word. It is suggested that the reason that the text starts with "Lorem" is because there was a page break spanning the word "Do-lorem". If you a re looking for a translation of the text, it's meaningless. The original text talks about the pain and love involved in the pursuit of pleasure or something like that.</p>
</div>
        {% endif %}
    <div class="container">
        <div class="row mx_auto">
            {% for Product in products.object_list %}
            <div class="my_bottom_margin  col-9 col-sm-12 col-md-4 xol-lg-4 ">
                <div class="card text-center" style="min-width:18rem;">
                    <a href="{{Product.get_url}}"><img class="card-img-left my_img" src="{{Product.image.url}}" alt="{{Product.name}}" width="100px;" height="100px;"></a>
                    <div class="card-body">
                        <h4>{{Product.name}}</h4>
                        <p>${{Product.price}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; New shop pvt ltd .All right reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'ecommerceapp:allprodCat' %}"></a><img src="{% static 'img/log.png' %}" alt="logimage" width="130px;" height="150px;">
  </center>
</header>

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'ecommerceapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="{% url 'ecommerceapp:allprodCat' %}">All Products</a></li>
          {% for Cat in links %}
          <li><a class="dropdown-item" href="{{Cat.get_url}}">{{Cat.name}}</a></li>

          {% endfor %}
        </ul>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <div>
    <form class="navbar-form navbar-left" action="{% url 'search_app:SearchResult' %}" method="get" >
     {% csrf_token %}
      <input   type="search" placeholder="Search" name="q"  aria-label="Search" >
      <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
      </div>
  </div>
</nav>

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        We have varity of products..
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
        <div class="row mx_auto">
            {% for Product in products %}
            <div class="my_bottom_margin  col-9 col-sm-12 col-md-4 xol-lg-4 ">
                <div class="card text-center" style="min-width:18rem;">
                    <a href="{{Product.get_url}}"><img class="card-img-left my_img" src="{{Product.image.url}}" alt="{{Product.name}}" width="100px;" height="100px;"></a>
                    <div class="card-body">
                        <h4>{{Product.name}}</h4>
                        <p>${{Product.price}}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx_auto">
                <p class="text-center my_search_text"> 0 results found</p>
            </div>
            {% endfor %}
        </div>
</div>
{% endblock %}